# -*- coding: utf-8 -*-
"""01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def max_min(*numbers):
  print(max(s1))
  print(min(s1))
s1 = [1, 3, 5, 88, -3]
max_min(s1)
