# -*- coding: utf-8 -*-
"""02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def reverse_string(s):
   return s[::-1]
s = 'Highwayman'
print(s)
a = reverse_string(s)
print(a)