# -*- coding: utf-8 -*-
"""03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def is_perfect(n):
  a = 0
  for i in range(1, n):
    if (n % i == 0):
      a = a + i
  if (a == n):
    return True
  else:
    return False

is_perfect(6)
