# -*- coding: utf-8 -*-
"""04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def is_prime(n):
    if n <= 1:
        return False
    elif n == 2:
        return True
    else:
        for i in range(2, n):
            if n % i == 0:
                return False
        return True
import math
n = int(input())
p = n + 1
while True:
   while is_prime(p) == False:
      p += 1
   else:
      print(p)
   break