# -*- coding: utf-8 -*-
"""05

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def count_upper_lower(s):
   s1 = 0
   s2 = 0
   for i in range(len(s)):
     if(s[i]>='a' and s[i]<='z'):
       s1 += 1
     elif(s[i]>='A' and s[i]<='Z'):
       s2 += 1
   return s1, s2
s = input()
count_upper_lower(s)