# -*- coding: utf-8 -*-
"""06

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def is_pangram(s):
  alphabet = "aelusivproft"
  for char in alphabet:
        if char not in s.lower():
            return False
  return True
s = 'elusive evasive persistent righteous traits for a rogue'
is_pangram(s)
