# -*- coding: utf-8 -*-
"""07

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def body_mass_index(m, h):
  m = int(weight)
  h = int(height)/100
  bmi = m/(h*h)
  bmi = round(bmi, 1)
  bmi_information(bmi)
def bmi_information(bmi):
  if bmi < 18.5:
        print('Underweight')
  elif (bmi > 18.5) and (bmi < 24.9):
        print('Normal')
  elif (bmi > 24.9) and (bmi < 29.9):
        print('Overweight')
  elif (bmi > 29.9):
        print('Obese')
  else:
        print('Error')
weight = int(input('Cân nặng:'))
height = int(input('Chiều cao:'))
body_mass_index(m, h)