# -*- coding: utf-8 -*-
"""08

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eb46QlBuaNI1dAe-8c4ZQrQBCXl8zR5I
"""

def change_upper_lower(s):
  a = s.swapcase()
  return a
s = input()
change_upper_lower(s)