# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7Yx-XYwS1EbCuvgpsC-CYv8ykwH3Xw5
"""

x = 1
y = 60
z = 0
import math
a = math.pi/6
F = (x+y+z)/(x**2+y**2+1)-abs(x-z*math.cos(a))
print(f'Gia tri cua F= {F}')