# -*- coding: utf-8 -*-
"""Bài 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rD0KI60ukBeWLk1GzdNlL2xxDfxil5kp
"""

name = input('Tên bạn là gì?')
print(f'Chào bạn {name} nhé')
year_born = input('Bạn cho mình biết bạn sinh năm nào được không?')
print(f'Bạn sinh năm {year_born} sao?')
a = int(year_born)
b = 2021
print(f'Vậy năm nay bạn {b-a} tuổi rồi!')