# -*- coding: utf-8 -*-
"""Bài 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WoYLfROtxZolKQZyRLYztkvDeWPIH1bd

- Có 4 kiểu dữ liệu dựng sẵn:
   + Bool
   + Number
   + Characters, string
   + Sequence, set, ...

- Bool:
"""

var = True
print(var)
print(type(var))
var = False
print(var)
print(type(var))

"""- Number:"""

var = 9+3j
print(var)
print(type(var))
var = 9.8
print(var)
print(type(var))

"""- Characters, string:"""

_str = '101'
print(_str)
print(type(_str))
_str = "Dien"
print(_str)
print(type(_str))

"""- Sequence, set:"""

set_ = {1, 2, 3, 4}
print(set_)
print(type(set_))
set_ = {'ncr, bos, cl, pg'}
print(set_)
print(type(set_))