# -*- coding: utf-8 -*-
"""01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mofQdbHMya-Wcw5d-MudAHqNI4SPb0TG
"""

_str = input('Hãy nhập gì đó:')
print(_str)
print(_str.replace(_str[0], "$"))