# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mE_nUnLhRY1DH7H5GC1SPcPhdtbQy0PA
"""

s = input("Hãy nhập gì đó:")
if len(s) >= 2:
  print(s[0:2] + s[-2:])
else:
  print("")