# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mE_nUnLhRY1DH7H5GC1SPcPhdtbQy0PA
"""

s = input('Hãy nhập gì đó:')
print(f'Kí tự lớn nhất: {max(s)}')
print(f'Kí tự nhỏ nhất: {min(s)}')