# -*- coding: utf-8 -*-
"""05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pXsBv3ZgamTydPPQei2Kue0m8NsoUUAE
"""

s = input('Hãy nhập gì đó:')
x = ''
for i in s:
  if chr(48) <= i <= chr(57):
    x += i
print(f'Các ký tự số trong chuỗi là: {x}')