# -*- coding: utf-8 -*-
"""06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_0UnMBz78IN639-Df6rcYAa8ewj1pEMT
"""

s = input('Hãy nhập gì đó:')
a = input('Nhập 1 kí tự:')
while len(a) > 1:
  print('Hãy nhập lại a:')
  a = input()
for i in range(len(s)):
  if s[i] == a:
    print(i, end=" ")