# -*- coding: utf-8 -*-
"""00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HqH0fA3q8WqVh39J8dWZdlNpMBMP6l3F
"""

class Books:
    def name(self, name):
        return name

b = Books()
print(type(b).__name__)

import random

def reroll_dice():
    a = random.randint(1,6)
    b = random.randint(1,6)
    s1 = a + b
    print(f'This time, you get {s1}')
    return s1

def roll_dice():
    n1 = random.randint(1,6)
    n2 = random.randint(1,6)
    print(f'Number is: {n1}, {n2}')
    f = 0
    s = n1 + n2
    return s

s = roll_dice()
if s == 7 or s == 11:
    game = 'Win'
    print('You win!')
elif s == 2 or s == 3 or s == 12:
    game = 'Lose'
    print('You lose!')
else:     
    print(f'Reroll! Your score is now {s}. To win, you must get the same score again, or lose upon getting 7! ')
    game = 'Continue'
while game == 'Continue':
  s1 = reroll_dice()  
  
  if s1 == s:
    game = 'Win'
    print('You win!')

  elif s1 == 7:
    game = 'Lose'
    print('You lose!')