# -*- coding: utf-8 -*-
"""01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HqH0fA3q8WqVh39J8dWZdlNpMBMP6l3F
"""

class Books:
    def name(self, name):
        return name

b = Books()
print(type(b).__name__)
