# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QM-1pZBW1_aDZ7bNWvuBtooWR3PPYvXu
"""

x = float(input('x='))
n = int(input('n='))
while n <= 0:
    print('Xin nhập lại n, với n là một số nguyên dương.')
    n = int(input('n='))
S_1 = S_2 = S_3 = 0
for i in range(0, n, 1):
  S_1 += x**i
  S_2 += (-x)**i
  S_3 += (x**i)/(math.factorial(i))
  i +=1
print(f'S_1= {S_1}')
print(f'S_2= {S_2}')
print(f'S_3= {S_3}')