# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QM-1pZBW1_aDZ7bNWvuBtooWR3PPYvXu
"""

n = int(input
        ('n='))
while n <= 0 or n >= 1000:
  print('Nhập lại n nguyên dương bé hơn 1000')
  n = int(input('n='))
Total = 0
while n > 0 and n < 1000:
  Total = Total + n % 10
  n = int(n//10)
print(f'Tổng các chữ số là: {Total}')