# -*- coding: utf-8 -*-
"""04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QM-1pZBW1_aDZ7bNWvuBtooWR3PPYvXu
"""

a = float(input('a='))
while a < 0:
  print('Nhập lại a dương:')
  a = float(input('a='))
b = float(input('b='))
while b < 0:
  print('Nhập lại b dương:')
  b = float(input('b='))
c = float(input('c='))
while c < 0:
  print('Nhập lại c dương:')
  c = float(input('c='))
if a+b>c and a+c>b and b+c>a:
  if a**2+b**2==c**2 or a**2+c**2==b**2 or b**2+c**2==a**2:
    print('a, b, c là độ dài 3 cạnh 1 tam giác vuông.')
  else:
    print('a, b, c là độ dài 3 cạnh 1 tam giác không vuông.')
else:
  print('a, b, c không phải cạnh của 1 tam giác')