# -*- coding: utf-8 -*-
"""05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QM-1pZBW1_aDZ7bNWvuBtooWR3PPYvXu
"""

import math
Epsilon = float(input('Epsilon ='))
while Epsilon >= 1:
  print('Nhập lại Epsilon bé hơn 1.')
  Epsilon = float(input('Epsilon ='))
e = 1
i = 1
if Epsilon <= 0:
  print('Không tính được e.')
else:
  while 1/math.factorial(i) >= Epsilon:
    e += 1/math.factorial(i)
    i += 1
  print(f'e = {e}')