# -*- coding: utf-8 -*-
"""00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nu79zK-Jc5N6GyajZZ7MBPs_uRlIijLR
"""

s = (1, 'acd', 5, 'f')
a, b, c, d = s
print(a)
print(b)
print(c)
print(d)
