# -*- coding: utf-8 -*-
"""01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C4szj1oOg9kcm2mA-TNS9Mmp7xpEg7b9
"""

a = [1, 2, 3, 4, 5]
b = (1, 2, 3, 4, 5)
print(tuple(a))
print(list(b))