# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjZeiB7-vaMf0MJKmOm59RygyHtDkLH-
"""

s = (1, 2, 3, 4, 5)
print(tuple(reversed(s)))