# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjZeiB7-vaMf0MJKmOm59RygyHtDkLH-
"""

s = [1, 2, 3, 4, 5, 6, 'assd', 'dsad', ('as', 'bn'), (1, 2, 3)]
count = 0
for i in s:
  if type(i) is not tuple:
    count += 1
print(count)