# -*- coding: utf-8 -*-
"""04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjZeiB7-vaMf0MJKmOm59RygyHtDkLH-
"""

def take_second(elem):
  return elem[1]
s = [(1, 0), (2 ,6), (3, 3)]
a = sorted(s, key=take_second)
print(a)