# -*- coding: utf-8 -*-
"""05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjZeiB7-vaMf0MJKmOm59RygyHtDkLH-
"""

def take_second(elem):
  return elem[1]
s = [(1, 0), (2 ,6), (3, 3), (6, -5), (-9999, 10)]
a = min(s, key=take_second)
print(a)