# -*- coding: utf-8 -*-
"""06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjZeiB7-vaMf0MJKmOm59RygyHtDkLH-
"""

s = (1, 3, 'Leper', 9, 'Stalwart', 'Shambler')
print(s[3])
print(s[-4])