# -*- coding: utf-8 -*-
"""07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jbd0qFbdRRIQfK2TEUYlHnPMmK398UGf
"""

def common_data(s1, s2):
    result = False
    for x in s1:
        for y in s2:
            if x == y:
                result = True
                return result
a = (1, 2, 3, "a", 'cs')
b = ("k", 6, 'jk')
print(common_data(a, b))