# -*- coding: utf-8 -*-
"""08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jbd0qFbdRRIQfK2TEUYlHnPMmK398UGf
"""

res = False
def check(s):
    if len(s) < 0 :
        res = True
    res = all(ele == s[0] for ele in s)
    if(res):
        print("Giống")
    else:
        print("Không Giống")
s = (1, 1, 1, 4)
check(s)