# -*- coding: utf-8 -*-
"""09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jbd0qFbdRRIQfK2TEUYlHnPMmK398UGf
"""

s = (1, 4, 9, -3, 2)
total = 0
for i in s:
  total += i
print(max(s))
print(total)