# -*- coding: utf-8 -*-
"""11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u4fphITdFGkkYQGXiy0pHoZP9VRCLeZy
"""

s = input('Nhập 1 câu nào đó:')
m = 0
for i in s.split():
  if (len(i)>m and i.isalpha() ):
    m = len(i)
    w = i
print(w)