# -*- coding: utf-8 -*-
"""12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sEhg2evYuWOdMIl17jjf2AS4pAjOZSbT
"""

s1 = {1, 4, 7, 2}
s2 = {1, 4, 7, 2}
s3 = {1, 4, 7, 2}
s4 = {1, 4, 7, 2}
s5 = {1, 4, 7, 2}
s6 = {1, 4, 7, 2}
s7 = {4, 2, 3, 5}
s1.difference_update(s7)
print(s1)
s2.intersection_update(s7)
print(s2)
print(s3.isdisjoint(s7))
print(s4.issubset(s7))
print(s5.issuperset(s7))
s6.symmetric_difference_update(s7)
print(s6)