# -*- coding: utf-8 -*-
"""05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-k5z6r3Qx3Qdd4QT_ASL6NJlvmTSpW4
"""

def file_read_from_head(fname, nlines):
        from itertools import islice
        with open(fname) as f:
                for line in islice(f, nlines):
                        print(line)

n = int(input())												
file_read_from_head('test.txt', n)
