# -*- coding: utf-8 -*-
"""06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezi6hppVvoeGo-5PSJum2IvHWCoxaiEs
"""

file_object = open('sample.txt', 'a')

file_object.write('yes')

file_object.close()