# -*- coding: utf-8 -*-
"""08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezi6hppVvoeGo-5PSJum2IvHWCoxaiEs
"""

def get_file_size(file):
  f = open('f:/file.txt')

  f.seek(0, os.SEEK_END)

  print('Size of file is', f.tell(), 'bytes')
