# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7Yx-XYwS1EbCuvgpsC-CYv8ykwH3Xw5
"""

x = float(input('x='))
y = float(input('y='))
z = float(input('z='))
import math
F = (x+y+z)/(x**2+y**2+1)-abs(x-z*math.cos(y))
print(f'Gia tri cua F= {F}')