# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NbeFsJB43HlRNMogpYvQAnlsKd_od0c-
"""

a = input('Nhập số nguyên a:')
b = input('Nhập số nguyên b:')
chia_lay_nguyen = int(a)//int(b)
chia_lay_du = int(a)%int(b)
print(f'Chia a cho b được phần nguyên là: {chia_lay_nguyen}')
print(f'Chia a cho b được phân dư là: {chia_lay_du}')