# -*- coding: utf-8 -*-
"""01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1In-nutghVo2fXNM3H8xOu0MZCIIimKWC
"""

class Dog:
    species = 'mammal'

    def __init__(self, name, age):
        self.name = name
        self.age = age
dog1 = Dog('Fake', 2)
dog2 = Dog('Mickey', 7)
dog3 = Dog('Fuk', 5)
def get_biggest_number(*args):
  return max(*args)
print(f'The oldest doggo is {get_biggest_number(2, 5, 7)} years old')
