# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12UmNK0hmA_hcFNw0fyEk0oD7KDivydjp
"""

s = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(random.choices(s, k = 5))