# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zkZYt0wV8T57v6Li8A29FHjtv54ToBXY
"""

s = [1, 2, 3, 4, 5, 6, 7, 8, 9, 100, -6, 5678, -98765]
print(max(s))
print(min(s))