# -*- coding: utf-8 -*-
"""06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12UmNK0hmA_hcFNw0fyEk0oD7KDivydjp
"""

lis = ['Jingle Jangle Jingle', 'heartaches by the number', 'Johnny guitar', 'ed-e']
count = 0
for i in lis:
  if len(i) > 2 and i[0] == i[-1]:
    count += 1
print('Số string trong list có hơn 2 kí tự và kí tự đầu giống kí tự cuối là:')
print(count)