# -*- coding: utf-8 -*-
"""10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S2aq1LLtCW6c47SfeYOvxp3D1BhqGvHm
"""

a = [1, 2, 3, 4, 5, 6, 7, 2, 4, 0, 12, 5, 1, 7, 7, 8]
print(len(sorted(set(a))))