# -*- coding: utf-8 -*-
"""00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10qTnqlF7esPrrnF1PmD5AV03Onp4puBf
"""

s = {'a': 12,'b': 15,'c': 20}
print(s)
total = 1
for key in s:
  total = total * s[key]
print('Tích các phần tử là:',total)
