# -*- coding: utf-8 -*-
"""01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hMH7WMZCSWRYv9hos3f-Cm7GV2ZLxk1Q
"""

s = {'x':50, 'y':54, 'z': 5}

max = max(s.keys(), key=(lambda k: s[k]))
min = min(s.keys(), key=(lambda k: s[k]))

print('Maximum Value: ',s[max])
print('Minimum Value: ',s[min])