# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hMH7WMZCSWRYv9hos3f-Cm7GV2ZLxk1Q
"""

s = {1: [1, 2, 3, 4, 5, 6, 7], 2: [2, 3, 4, 5, 6, 7, 8], 3: [3, 4, 5, 6, 7, 8, 9], 4: [-3, -2, -1, 0, 1, 2, 3]}
print((s[1])[4])
print((s[2])[4])
print((s[3])[4])
print((s[4])[4])
