# -*- coding: utf-8 -*-
"""05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hMH7WMZCSWRYv9hos3f-Cm7GV2ZLxk1Q
"""

s1 = {
    1: [2, 6, 9],
    2: [1, 3, 5],
    3: [0. -2, -4],
    'a': ['a', 'b', 'cds']
}
s2 = {
    2: [1, 3, 5],
    'a': ['a', 'b', 'cds'],
}
for i in s1:
    if i in s2:
      if s1.get(i) == s2.get(i):
        print(i, ':', s1.get(i))

s1 = {
    1: [2, 6, 9],
    2: [1, 3, 5],
    3: [0. -2, -4],
    'a': ['a', 'b', 'cds']
}
keys = [1, 'a']
s2 = {k: s1[k] for k in keys}
print(s2)