# -*- coding: utf-8 -*-
"""08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uqw8JZ-hdjAZcV8-QlIfAXnrqrhixsC
"""

s = ('Python is one of many types of programming languages')
a = s.split(' ')
print(s)
b = {}
for i in a:
    if i in b:
        b[i]+=1
    else:
        b[i]=1
for i in sorted(b, key=b.get, reverse=False):
       print(i, b[i])