# -*- coding: utf-8 -*-
"""09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uqw8JZ-hdjAZcV8-QlIfAXnrqrhixsC
"""

input = [{'item': 'item1', 'amount': 400}, {'item': 'item2', 'amount': 300}, {'item': 'item1', 'amount': 750}]
output = {}
for i in input:
  name = i['item']
  amount = i['amount']
  if name in output:
    output[name] += amount
  else:
    output[name] = amount
print(output)